### ISSUE TITLE
Graphical issue in gtk3 branch

### ISSUE THREAD

**Issue by Mjolinir** [asbru-cm/asbru-cm#326]
OS: Fedora 31 (with nvidia drivers from rpmfusion)
Kern: 5.3.16-300
Desktop: i3-gaps, KDE
Asbru: 6.0.0 (gtk3 branch)

Issue: When opening more than 1 RDP sessions, the previous tabs are no longer readable due to a graphical glitch of some kind. The Windows RDP session that was just opened continues to work fine, but if you click on any of the previous tabs, they are unreadable and only contain the underlying connection information from asbru. I will attach screenshots to show what I see.

Screenshot1 shows the newest tab just opened, and as you can see, it looks normal, at least for now. eventually the glitch will affect this tab as well.

![Screenshot1](https://user-images.githubusercontent.com/7074712/71670618-6c837c00-2d3e-11ea-96ac-41c552cc89b9.png)

Screenshot2 shows the first tab that was a previously opened session. It is no longer readable and displays text similar to an ssh session. You can see the very top of the Windows desktop background at the very top. I have found no way to refresh the window contents. Opening additional sessions does the same thing to previous session tabs.

![Screenshot2](https://user-images.githubusercontent.com/7074712/71670624-71483000-2d3e-11ea-8aa7-036cacd2681b.png)

**Comment by gfrenoy** [comment]
Thanks for your feedback @Mjolinir, I do confirm : if you start any other terminal ; the RDP message window is shown (but it should not...).

I'm looking into it ...

In the meantime you can click on the "Show messages" button to display the whole RDP window again:
![image](https://user-images.githubusercontent.com/981546/71750714-9bead380-2e79-11ea-8b63-d195874e720f.png)

**Comment by gfrenoy** [comment]
Just push [a change](https://github.com/asbru-cm/asbru-cm/commit/ca7f5bc1d4a5aff202649b409236bb13c6e20531) that should fix the issue.

For some reason (and since a long time...), every time you start a new connection, it was showing all panels of all already open connections.  No reason for this.  I removed the line.

Let us know if it helps in your case...

**Comment by Adorid** [comment]
In linux mint started to work correctly

**Comment by Mjolinir** [comment]
I updated this morning, unfortunately the problem still exists for me (in Fedora). I will test RHEL7/8 and Arch as well

**Comment by gfrenoy** [comment]
@Mjolinir can you confirm you are using the latest snapshot (v6.0.2) ?

**Comment by Mjolinir** [comment]
when I click the about button, it just says v6.0.0. I did a git pull right before posting this

**Comment by gfrenoy** [comment]
@Mjolinir can you switch match to the master branch ?  We don't work on the gtk3 branch anymore...

**Comment by Mjolinir** [comment]
I can, sure. I don't experience the issue in the main branch, only the gtk3. So should I stop using gtk3 branch? I was using it because you guys asked me to in another thread.

**Comment by KlaasT** [comment]
Yes please use the master in the future. We merged gtk3 some time ago into master and gtk3 will be archived very soon.

**Comment by Mjolinir** [comment]
Done, I have switched back to the master version and removed all gtk3 branch artifacts

**Comment by KlaasT** [comment]
What about the graphical issues are these still there?

**Comment by Mjolinir** [comment]
In the gtk3 branch, yes, but I never encountered them in the other branch

**Comment by KlaasT** [comment]
Okay. Then I will close that one for now. As said the gtk3 branch will be archived and everything has been merged into master. Feel free to reopen if this is happening again.
