### ISSUE TITLE
Jump Host Feature: unable to estabilish connection, Missing user name in temp ssh configuration; 

### ISSUE THREAD

**Issue by danielemay** [asbru-cm/asbru-cm#463]
**Describe the bug**
I Created a new connection using the Jump Host Feature, using private key for jump host and user/pwd for final host;
When connecting an error appear blocking the connection;
the final host username isn't forwarded in the temporary ssh configuration, blocking the connection attempt.

**Expected behavior**
Connection should be enstabilished.

**Screenshots**
![Screenshot_20200312_101851](https://user-images.githubusercontent.com/32195311/76507299-da3dd980-644c-11ea-94c6-116ec0add418.png)
![Screenshot_20200312_101908](https://user-images.githubusercontent.com/32195311/76507497-3274db80-644d-11ea-9c27-39be00162218.png)
![Screenshot_20200312_101923](https://user-images.githubusercontent.com/32195311/76507503-36086280-644d-11ea-9071-4c6dd4e43c5d.png)
![Screenshot_20200312_102030](https://user-images.githubusercontent.com/32195311/76507510-37d22600-644d-11ea-9b4f-e240ad6d1545.png)

**Desktop (please complete the following information):**
Linux 20190458-AIT 5.4.23-1-MANJARO #1 SMP PREEMPT Fri Feb 28 22:45:29 UTC 2020 x86_64 GNU/Linux

**Additional context**
Using Asbru Loki Version

**Comment by hanspr** [comment]
The problem is in the user of the connection.

![imagen](https://user-images.githubusercontent.com/1572396/76535312-482fd400-6440-11ea-919e-2bb853abe1c4.png)

And by the litle information I can see in the red square, you must be using keepass. And the must current nightly build

If using KeyPass, then your current KeyPass settings are no longer compatible with the new implementation.

Your options right now:

1. Read the merge of this changes at #349 , to see how it works now.
   1. Basically, clic on the keypass button icon, and locate the entry that holds the current username and password for that connection.
    1. I'm in the process of documenting everything and this manual page is the next one, hope I'll have it by tomorrow, and then depends on the merging of documentation.
1. Write the user name and passwords directly in the fields, while you learn and reconfigure the new keepass implementation.

__Note__ : You must have installed keepassxc-cli ("KeePassXC") for this implementation to work.

**Comment by hanspr** [comment]
After PR #464 is merged, an hour later you may check the documentation of the new keepass integration to see how it works.

https://docs.asbru-cm.net/

Or on the buttons that we are adding at the top right of every preference tab, that button should open the corresponding help page of the section you are located.

**Comment by danielemay** [comment]
Hi hanspr,
thanks for the quick answer!

yes, I'm using the latest version installed by AUR;

the main problem is not the keypass auth, i made the screenshot with the latest settings used, but I've already tryied all kind of settings with no result;
I use it mainly with simple username & password but i found username problem and then i cannot connect; only way i found is to use the 'old' ProxyCommand but it is very annoying cause it doesn't pass the login information

btw the problem happen when i choose to use the new jump host feature, and in that case no matter what I check in the connection details,  it gives me the Missing Argument error

thanks in advance,
tell me If i can hel sending you some configuration or other piece of config that can help resolve the issue

;)

**Comment by hanspr** [comment]
There is an option to export the configuration for debugin that exports the configuration file removing the sesitive information, if you can export that file and uploaded or send it to my public email account @hanspr 

https://docs.asbru-cm.net/Manual/Preferences/Preferences/

Check the file before uploading to see that we did remove all sensitive data.

I have not been able to reproduce using the settings in your image.

**Comment by hanspr** [comment]
Ok, found the error, as a workaround while I fix this

1. Enable the Private Key option
1. Write the user name there
1. Select User/Password again
1. Save

![imagen](https://user-images.githubusercontent.com/1572396/76628695-c18ffb00-6502-11ea-9ce1-5f308f04ddb8.png)

Right now is taking in consideration that password so is ignoring the one you are selecting.

I will send a fix soon.

**Comment by danielemay** [comment]
Hi!

yup, I tryed too and I can confirm that the workaround is working ;)

IMHO I think that to complete the scenarios and fully use this feature a few improvement need to be added:

- there should be the possibility to connect to JH with user/pwd other than private.key 
- in case of use private.key, there is the need to use the passphrase if the key is protected ( a field like the one in Connection Detail would be fine)

actually i'm using the second option and I found that PAC fill the JH key passphrase with the password filled for the final host

actually (before the option you suggested) i solved using advanced ssh options passing ProxyJump with a pre-configured session filled in my .ssh/config file

Since recently I'm heavily using asbru just tell me if I can help someway with testing these features ;)

Cheers ! ;)

btw here an exported configuration in case could be useful:

```
---
8be8551b-b2ef-42d8-8eba-495a80c9f127:
  KPX title regexp: .*HOST.*
  _is_group: 0
  _protected: 0
  auth fallback: 1
  auth type: userpass
  autoreconnect: ''
  autossh: ''
  children: {}
  cluster:
    - wq
  description: Connection with 'HOST'
  embed: 0
  expect: []
  favourite: 0
  infer from KPX where: 3
  infer user pass from KPX: ''
  ip: x.x.x.x
  jump ip: x.x.x.x
  jump key: /path/to/file.key
  jump port: 22
  jump user: jump-user
  local after: []
  local before: []
  local connected: []
  mac: ''
  macros: []
  method: SSH
  name: 'Hostname to connect'
  options: ' -x -C -L 8887:localhost:8887'
  original_parent: 6d1e2cfb-fc09-4419-be73-0ec149ed417b
  parent: __PAC__EXPORTED__
  pass: password
  passphrase: ''
  passphrase user: ''
  port: 3022
  prepend command: ''
  proxy ip: ''
  proxy pass: ''
  proxy port: 8080
  proxy user: ''
  public key: ''
  quote command: ''
  remove control chars: ''
  save session logs: ''
  screenshots: ~
  search pass on KPX: 0
  send slow: 0
  send string active: ''
  send string every: 60
  send string intro: 1
  send string txt: ''
  session log pattern: <UUID>_<NAME>_<DATE_Y><DATE_M><DATE_D>_<TIME_H><TIME_M><TIME_S>.txt
  session logs amount: 10
  session logs folder: /home/daniele/.config/pac/session_logs
  startup launch: ''
  startup script: ''
  startup script name: sample1.pl
  terminal options:
    audible bell: ''
    back color: '#000000000000'
    bold color: '#cc62cc62cc62'
    bold color like text: 1
    command prompt: '[#%\$>]|\:\/\s*$'
    cursor shape: block
    disable ALT key bindings: ''
    disable CTRL key bindings: ''
    disable SHIFT key bindings: ''
    open in tab: 1
    password prompt: "([pP]ass|[pP]ass[wW]or[dt](\\s+for\\s+|\\w+@\\w+)*|[cC]ontrase.a|Enter passphrase for key '.+')\\s*:\\s*$"
    tab back color: '#000000000000'
    terminal backspace: auto
    terminal character encoding: UTF-8
    terminal font: Monospace 9
    terminal scrollback lines: 5000
    terminal select words: -.:_/
    terminal transparency: 0
    terminal window hsize: 800
    terminal window vsize: 600
    text color: '#cc62cc62cc62'
    timeout command: 40
    timeout connect: 40
    use personal settings: ''
    use tab back color: ''
    username prompt: '([lL]ogin|[uU]suario|[uU]ser-?[nN]ame|[uU]ser):\s*$'
    visible bell: ''
  title: Hostname to connect
  use prepend command: ''
  use proxy: 3
  use sudo: ''
  user: username
  variables: []
__PAC__EXPORTED__:
  children:
    8be8551b-b2ef-42d8-8eba-495a80c9f127: 1

```

**Comment by hanspr** [comment]
A PR with the change has been merged, and there will be a new release soon.

> there should be the possibility to connect to JH with user/pwd other than private.key
> in case of use private.key, there is the need to use the passphrase if the key is protected ( a field like the one in Connection Detail would be fine)

As far as we investigated, the jump just option (ssh -J) has to be configured to use keys and passwordless. That is why it was implemented like this. The final destination can have any authenticating method.

**Comment by popxunga** [comment]
Sorry to hijack this discussion, but stupid or not, sometimes the key exchange process necessary to use a normal jump server is just not allowed by enterprise rules.
So as suggested above, having the chance to use what I would call a pseudo-jump server, would be nice. By pseudo-jump server I mean just a another connection to a server where we authenticate with userid/password, and once logged-in there we ssh to the final destination server. 
This said, having something like follows may help a lot:
![image](https://user-images.githubusercontent.com/37672088/76653254-3e04f700-6560-11ea-9934-1f6cd16b79ac.png)
The rectangle is a combo box from where we would select the intended pseudo-jump server. So it should be filled with list of defined connections.
Thanks.

**Comment by hanspr** [comment]
Hi @popxunga 

I understand that, but at the same time, the matrix of possibilities with ssh is tremendous.
And I do not know if we could be able to accommodate all of them using options and configurations.

I have implemented the solution that you mention configuring expect in that particular connection.

You login to the first server and then add expect rules to:

* Wait for the prompt
* Execute and ssh command to open a session on the next server.

You could open a new feature request and lets see.

**Comment by popxunga** [comment]
> Hi @popxunga
> 
> I understand that, but at the same time, the matrix of possibilities with ssh is tremendous.
> And I do not know if we could be able to accommodate all of them using options and configurations.
> 
> I have implemented the solution that you mention configuring expect in that particular connection.
> 
> You login to the first server and then add expect rules to:
> 
>     * Wait for the prompt
> 
>     * Execute and ssh command to open a session on the next server.
> 
> 
> You could open a new feature request and lets see.

Yeap ... that's what I do since a long time.
But its not nice when the password of the pseudo-jump server expires, and you use that server to jump to another dozen of servers. I do have to edit the 12 connections to put the new password.

**Comment by hanspr** [comment]
> I do have to edit the 12 connections to put the new password.

Options:

* use a global variable for this (not tested, not very safe) : https://docs.asbru-cm.net/Manual/Preferences/GlobalVariables/
* Use keepass and link the password to your jump server, you change your password in keypass and you just change the password at one point. https://docs.asbru-cm.net/Manual/Preferences/KeePassXC/

You will make me write another "Article" in the documentation site :wink: 

Ain't a beauty to have online documentation?

>  Do you want me to put this as a new feature request ?

Click on __new issue__, select "feature request"

![imagen](https://user-images.githubusercontent.com/1572396/76655209-670e9300-6532-11ea-957c-fd1d517c0fb0.png)

**Comment by hanspr** [comment]
@danielemay 

Could you remove the workaround and confirm if this has been fixed with the latest released changes?

**Comment by danielemay** [comment]
Hi @hanspr ,

sure!
I've done the test and I can confirm that now it works and not die anymore on the configuration problem ;)

Despite this, actually I can't use that feature cause I'm using a rsa key with passphrase cause in this case i need to put the 2 different password manually:

![image](https://user-images.githubusercontent.com/32195311/77051985-74ad9800-69cc-11ea-9e7a-e1029d9bfa4f.png)

![image](https://user-images.githubusercontent.com/32195311/77052001-79724c00-69cc-11ea-8eaf-962d5e96a8b7.png)

If you look at the connection log it uses correctly the -J option, but cause the problem of the passphrase, it use the FinalHost password in the phassprase getting a denied response and then asking to put it manually ( so you can see two different entry to put the key passphrase and then the FinalHost password )

 It seem that it doesn't parse correctly which password is asked, maybe to solve should be useful that the connector may recognize the two different prompt and then put the correct passwords

**Comment by hanspr** [comment]
The jump server need a password less publick key will not work if the jump server demands a passphrase, remove the password on you local key, and it should work.

**Comment by merikz** [comment]
Hi,
So, working from home due to corona, and started using jump host and stumbled on this bug on asbru-cm v6.1.0-rc1, so it's not just in loki.
Can this fix be released quicker than ...whatever release current loki is targeted, please?

I guess I'm not the only one just started working from home.

**Comment by hanspr** [comment]
I don't know how fast can it be changed, but the workaround for the moment would be to remove the passphrasse for your jump server key, or at least for that connection.

**Comment by merikz** [comment]
I forgot to mention; I don't use Keepass for this.
I don't use passphrase for the key, and only user+pwd to the target host.

It works for "old" connections, created on v6.0.4 (I believe, at least before v6.1.0rc1), but this bug (no User in the conf file) happens for newly created connection.

**Comment by hanspr** [comment]
@merikz 

If you are referring to the original bug in the title, then get the new release, it should be fixed already.

https://github.com/asbru-cm/asbru-cm/releases/tag/6.1.0rc2

If you are referring to the have a passphrase for the jump server, I don't know how long it will take.

**Comment by hanspr** [comment]
Or install the nightly build (I'm not sure how those thinks work, but apparently those images are created after a few hours of a merge) but as well could have some new bugs.

**Comment by merikz** [comment]
I'm referring to the empty User in the generated .conf file, and the ensuing "Missing argument".
I still get that, after upgrading to v6.1.0rc2

Can you direct me to the line/sub/commit-id responsible for this, so I can quickly hack it? 
I'm not familiar with the jumphost code.

I'm not keen on installing nightly build on my work computer. I'd like to keep that one stable, but this disturbs  my workflow quite a bit. 
There are quite a few commits (lots!) differing between loki and rc2.

(Sorry I have not been very active with asbru lately. Work steal my attention.)

**Comment by hanspr** [comment]
Above is a temporay work arround:

https://github.com/asbru-cm/asbru-cm/issues/463#issuecomment-598741832

If you want to fix it in your current code, this is the commit link

https://github.com/asbru-cm/asbru-cm/pull/469/files

 Implement those changes and should work

**Comment by merikz** [comment]
@hanspr 
Thanks!
applying this on top of v6.1.0rc2 solves it.
https://github.com/asbru-cm/asbru-cm/pull/469/files

@KlaasT 
Can this be released as an rc3 or something? The updated Proxy is quite new and was really useful until rc1 broke it. Would be nice to get it working in v6.1.0.
I guess release of loki comes long after v6.1.0, right?

**Comment by gfrenoy** [comment]
Fix has been applied to 6.1 ; we'll release it soon...

**Comment by gfrenoy** [comment]
Is now available in the latest 6.1.2.
