### ISSUE TITLE
Pasting long passwords into password prompt doesn't always work

### ISSUE THREAD

**Issue by yennor** [asbru-cm/asbru-cm#49]
Ok, I know, the whole error description sounds very unlikely, but unfortunately that's how it is:

I use keepassxc to automatically create passwords, usually they are 20 characters long.
Sometimes (not always), when a programm shows me in a ssh console a password prompt (those linux prompts, where you don't see what you type or how many characters), when I paste the password (middle click, or using the context menu), it will not accept the password. Doesn't matter how many times I try. The only solution is to either:
- Write the password by hand
- with some programms i can give the parameter directly on the command line as parameter (like "-w passwordstring10928374"). Even when I paste it there, it perfectly works.
- open a new connection in a new tab to exactly the same server, and then pasting works again (most of the time).

It even happens for connections, where I don't use an ssh key, but on opening the connection, the server asks me to enter the passwrod.
I've already lost hours like that, since I thought that I've got the wrong passwords...
It only seems to happen with long passwords, it seems like I never had the same problem with short ones. But I can't be completely sure, since I seldom use short passwords (that's what you've got a password manager for).

If there is anyway I can help in debugging that, I gladely would. It's driving me nuts!

edit: I'm using debian stable (stretch 9), and asbru 5.0.0

**Comment by gfrenoy** [comment]
What happens if you do the same when you can see what it types ?  I mean: does it also sometimes do not paste what is expected ?

Another question : what if you use the shortcut key "CTRL+SHIFT+V" ?  Same issue or different behaviour ?

**Comment by yennor** [comment]
Where I can see what it insert, it always inserts the correct text. Even
if it just a second before inserted the wrong text to the password prompt.

I'm 100% sure I've tried it out with a middle click, and the context
menu paste. I'm only about 90% sure I also tried out ctrl+shift+v .
But right now the problem doesn't appear, and I should do some work..
But as soon as it happens again I will try it out for sure.

I just remembered, in previous versions of asbru-cm (pac), it could
happen that when pasting text that it was inserted something like
~0pastedText~1
I didn't see that happen in a while. But maybe when that bug was solved
(if it was solved), it was solved in a way, that sometimes still some
extra characters are pasted, but invisible ones? So that when I can see
what it inserts they are not shown, but the password prompt complains
about it?

**Comment by gfrenoy** [comment]
Thanks for your feedback, let's wait and see if it happens again.  To get a valid long-term fix, we need to understand the exact issue so if you can find a way to reproduce it ... That'll really help !

**Comment by yennor** [comment]
just yesterday, i had the bug again, that when I paste something that at 
the beginning it puts a "~0" and at the end a "~1" (or maybe it was "0~" 
and "1~". Just opening a new tab with a new connection makes it work again.
But I had a customer at the phone, so I couldn't investigate... But 
maybe that is related?
I will investigate more, but right now, I'm near a deadline in a 
programming project, so I don't do anything with ssh...

**Comment by merikz** [comment]
I remember the same problem in old pac versions. It is probably same as what is described in these old reports on pac:
[paste problem](https://sourceforge.net/p/pacmanager/discussion/1076055/thread/ac548112)
[#243 copy/paste garbage / bracketed paste mode](https://sourceforge.net/p/pacmanager/bugs/243/#1711)

That was a vte bug, but the reports don't say how it was finally fixed in pac. I never saw any source code for the vte.so files that was shipped in pac, but maybe it was fixed in those?

I haven't seen the problem in asbru, but here's an idea for a possible workaround; 
As there are some hints in the referenced threads towards switching between the two vte screen buffers, maybe starting+exiting vi makes a difference? 
That resets vte to use the scrollback enabled buffer, and perhaps also affects the bracketed paste mode? (The same reset can be achieved with "less --help" + "q".)
The local terminal and remote tty can get out of sync for example at connection loss to a remote ssh node, typically when you're in less or vi to look at/edit a file on the remote machine.

**Comment by yennor** [comment]
ok I accidentally found out how to reproduce it!
1. Start an ssh connection.
2. try out your opening an ssh connection from that console by pasting the password => works
2. start midnight commander "mc"
3. exit midnight commander "exit"
4. try out connection again to the connection from point 2 by pasting the password =>  does NOT work anymore.

I don't know if there are other ways to trigger that problem. at least like that i can trigger it.

**Comment by AdrianBan** [comment]
Hi,

I can confirm this. I have the same issue with multi-line copy-paste. After entering and exiting from "mc" the CR is not send after each new line.

Steps:


Steps to reproduce the behavior:
1. Open a console
2. Open a text editor
3. Write down few lines, like:
```
ip a l ens192
ls -l
```
4. Start mc in the console and exit.
5. Copy the commands from text editor.
6. Paste into the console.
7. Output:
```
root@Cacti:~# mc

root@Cacti:~# ip a l ens192
ls -l

2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:d7:0d:61 brd ff:ff:ff:ff:ff:ff
    inet 89.xx.xx.169/27 brd 89.xx.xx.191 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 2a00:ece1:2:0:20c:29ff:fed7:d61/64 scope global mngtmpaddr dynamic 
       valid_lft 2591889sec preferred_lft 604689sec
    inet6 fe80::20c:29ff:fed7:d61/64 scope link 
       valid_lft forever preferred_lft forever
total 73244
```

**Comment by gfrenoy** [comment]
Thanks for your comment Adrian.  I gave it a try on my side but I do not observe the same thing.  But I must admit I already experimented some "weird" behaviors that are always magically fixed by a "reset".

And as a "reset" does fix the problem, I always thought the issue was outside Ásbrú ...

**Comment by yennor** [comment]
the problem still consists and it's at least reproducible by me and adrian. Meanwhile I've updated my System to Debian Buster, but the Problem is still here.
Just had a problem with a client since the password I've created for him didn't work, exactly for the above problem.
I can confirm that reset solves the problem.
And the problem only appears when opening an ssh connection out of asbru-cm, never when I open the ssh connection directly from a console. So it seems to be a problem in asbru-cm or one of it's dependencies. Maybe since gfrenoy doesn't have the same problems, it could depend on one of the dependencies which only show that behaviour in a certain version?
Unfortunately I don't know how I could give you any more feedback...

**Comment by gfrenoy** [comment]
Can you try to reproduce this in [VTE](https://gitlab.gnome.org/GNOME/vte/) only, see instructions here:
  https://github.com/asbru-cm/asbru-cm/issues/143#issuecomment-486843120
?

**Comment by yennor** [comment]
I tried it out using the perl script.
I get the exactly same behaviour.
If I understand the other thread correctly, it means it is a VTE bug?

**Comment by gfrenoy** [comment]
Yes I do fear so.

Can you submit an issue to that project : https://gitlab.gnome.org/GNOME/vte/issues ?

**Comment by yennor** [comment]
alright, I've posted a bugreport. Let's hope for the best:
https://gitlab.gnome.org/GNOME/vte/issues/126

**Comment by yennor** [comment]
that was quick. I guess there's nothing we can do :-( (Besides applying the provided patch to libvte myself)
here the answer:

This was fixed 5 years ago: https://bugzilla.gnome.org/show_bug.cgi?id=729533

VTE 0.28.2 is 8 years old, the last from the GTK2 series which is no longer maintained. It'll hopefully soon be dropped from Debian, Ubuntu and hopefully other major distros too.

asbru-cm should switch to GTK3 and thus a much newer, actively maintained VTE (0.56 at the moment), including hundreds of bugfixes, improvements and new features since 0.28.

**Comment by merikz** [comment]
The bugzilla has a [comment](https://bugzilla.gnome.org/show_bug.cgi?id=729533#c6) with a fix for vte 0.28.2, made by @nerijus for pacmanager back in the days. (Maybe that was [somehow](https://github.com/asbru-cm/asbru-cm/issues/49#issuecomment-372070133) delivered with pacmanager?)

Since the refactoring of Gnome2::Vte usage in asbr-cm, I don't suppose @KlaasT can do something here through libgnome2-vte-perl?

**Comment by nerijus** [comment]
vte-0.28.2-27.fc30 in Fedora does have the fix for it - just downloaded vte-0.28.2-27.fc30.src.rpm and checked that it has vte-0.28.2-paste-fix.diff inside, which is the same as in https://bugzilla.gnome.org/show_bug.cgi?id=729533#c6

**Comment by gfrenoy** [comment]
Thanks all for your contributions, it makes things much clearer now :)

In libgnome2-vte-perl, we don't build the VTE package but the perl binding only so I do fear there's nothing we can do there.

So our two options are:

1) building and providing the VTE package
2) work on the GTK3 migration

Option 2 looks the most appealing but how can we structure this kind of project and what resources do we have to achieve it ?

I can and would like to help a bit (for sure) but I cannot support the whole thing alone...

**Comment by zarej** [comment]
The workaround can be whenever copy/paste is not working to execute the command `reset` to reset terminal. After that everything is back to normal.

**Comment by yennor** [comment]
that only works if you notice it. It already happened several times, 
that I've set new passwords, using copy'n paste. You don't notice then 
that the password is set wrongly. Only afterwards (could be a while 
later), when you try to login using that password, and you just can't 
figure out why it doesn't work...

**Comment by IAMtheIAM** [comment]
How do I change the keyboard shortcuts? I do not like ctrl+shift+c/v - it should be without shift! it makes it super awkward.

Everything else is great though with Asbrucm!

**Comment by gfrenoy** [comment]
> How do I change the keyboard shortcuts?

Not possible but this should not be discussed here.  Please keep the discussion on the same topic !

> Everything else is great though with Asbrucm!

Thanks, it is great because everyone single one of us ; any detail of any contribution is possibly important.

**Comment by gfrenoy** [comment]
There is now a "beta" version of Ásbrú Connection Manager based on the newer version of VTE that should have fixed this issue.

See https://github.com/asbru-cm/asbru-cm/tree/gtk3#testing-the-gtk3-branch for instructions to test it.

Feel free to re-open the issue if required.
