### ISSUE TITLE
vertical split wrongly aligned when tabs are on right side

### ISSUE THREAD

**Issue by vibo69** [asbru-cm/asbru-cm#646]
as in topic. probably the same will be observed with tabs on the left. latest loki

**Comment by gfrenoy** [comment]
Would you mind providing a bit more context ?

I think a screenshot, the version you are using and what you mean by "tabs are on right side" would really help understanding your issue better.

Thanks.

**Comment by vibo69** [comment]
by tabs I mean opened terminals list. below is an example. looks like 'center' is calculated without including tabs width. screenshot starts from the end of connection list and ends at tabs start. clearly 'center' is not at center ;) 
![obraz](https://user-images.githubusercontent.com/33600494/84104254-71e3a180-aa15-11ea-9ad4-080839d3b2a2.png)

**Comment by gfrenoy** [comment]
Ok got it !  Thanks for the additional info.

**Comment by gfrenoy** [comment]
This should be fixed in the next loki build (that will be ready in about 15 min).  Let me know if it works for you !

**Comment by vibo69** [comment]
this one? asbru-cm (6.3.0~1591688118-1) (i see also this one has added ncat for deps). problem still exists

**Comment by gfrenoy** [comment]
> this one? asbru-cm (6.3.0~1591688118-1) 

No, this one is older (4 hours ago) ; if you are using ubuntu/bionic, it should  asbru-cm_6.3.0~1591700418-1 (less than 1 hour ago).

Can you try again ?

**Comment by vibo69** [comment]
now its splited equally ;) does this split is calculated dynamically? just curious because size of tabs changes depending on hostname lengths of active connections

**Comment by gfrenoy** [comment]
> now its splited equally ;) 

Good, thanks for the feedback.

> does this split is calculated dynamically?

It's calculated once at creation time.

Then it is re-caculated automatically only if you have the option "Force split tabs to 50%" checked in Preferences > Main Options > Behaviour:

![image](https://user-images.githubusercontent.com/981546/84146728-6ff10100-aa5c-11ea-8627-c54a30d985ad.png)

(otherwise, no it is not recalculated)
